import = [
	"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
dimensions = { columns = 110, lines = 36 }

[font]
size = 16.0

[font.normal]
#family = "ProFont for Powerline"
#family = "Hack"
#family = "Source Code Pro for Powerline"
family = "Agave Nerd Font" 
style = "Regular"
