import = [
	"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
dimensions = { columns = 110, lines = 31 }

[font]
size = 14.0

[font.normal]
#family = "ProFont for Powerline"
#family = "Hack"
family = "Source Code Pro for Powerline"
style = "Regular"

[font.bold]
#family = "ProFont for Powerline"
#family = "Hack"
family = "Source Code Pro for Powerline"
style = "Bold"

[font.italic]
#family = "ProFont for Powerline"
#family = "Hack"
family = "Source Code Pro for Powerline"
style = "Italic"

[font.bold_italic]
#family = "ProFont for Powerline"
#family = "Hack"
family = "Source Code Pro for Powerline"
style = "Bold Italic"
