import = [
	"~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
dimensions = { columns = 130, lines = 40 }

[font]
size = 16.0

[font.normal]
#family = "ProFont for Powerline"
#family = "Hack"
#family = "Source Code Pro for Powerline"
family = "Agave Nerd Font" 
style = "Regular"
