customCommands:
  - key: 'O'
    context: 'status, files, worktrees, submodules'
    command: 'git-open {{.Form.Branch}}'
    description: 'Open current repository on the browser'
    prompts:
      - type: 'menu'
        title: 'In which branch do you want to open?'
        key: 'Branch'
        options:
          - name: 'master'
            description: 'Open repository in master'
            value: 'origin master'
          - name: 'current branch'
            description: 'Open repository in current branch'
            value: ''
  - key: 'C'
    context: 'status'
    command: 'code .'
    description: 'Open current local repository on Visual Studio Code'
  - key: 'F'
    context: 'status'
    command: 'nautilus .'
    description: 'Open current local repository on File Explorer'
